### ISSUE TITLE
WebStorm freezes when opening nx.json (Generating Graph)

### ISSUE THREAD

**Issue by petterhoel** [iguissouma/nx-console-idea-plugin#53]
On opening `nx.json` WebStorm freezes. It is stuck on something called _Generating Graph._ I am unsure what feature that is, I am just trying to open the json file. Sometimes beach ball arrives. Every time force quit is only escape. It is happening on existing code bases and I just reproduced the issue on a brand new project running `npx create-nx-workspace --preset angular`. Issue goes away when disabling Nx Console Idea and restarting WebStorm. Here is a recorded screen capture:

![ws-freeze](https://user-images.githubusercontent.com/1263775/148811636-74c9efff-7049-4ee2-a75a-289a24476b4b.gif)

MacOs 12.1
M1 processor
Webstorm 2021.3.1
Nx Console Idea 0.36.0

It also happens in my Windows 10 work machine, but there I explicitly have to click the graph tab at the bottom after opening `nx.json` to trigger the bug. 

The bug has been present in an few patches/minor versions of WebStorm and Nx Console Idea, but I do not know exactly when it started. 

Thanks for a great plugin btw 😄

**Comment by iguissouma** [comment]
I will see how to fix it.
The feature shows you the dependency graph.
As a workaround maybe Check the filetype association of nx.json or open it as plain text.
Thanks for reporting this.

**Comment by petterhoel** [comment]
Thanks! If anyone else hits this I can confirm that setting file pattern `nx.json` to filetype txt is a good workaround. 
![image](https://user-images.githubusercontent.com/1263775/148972070-30b813b8-d9ad-46ae-9bcd-2dde801367f2.png)

**Comment by iguissouma** [comment]
should be working again on next version

<img width="1235" alt="Screenshot 2022-02-03 at 13 49 52" src="https://user-images.githubusercontent.com/9085108/152346196-589fefc5-1551-4af2-8f8b-fffd80f661d9.png">

**Comment by petterhoel** [comment]
Next version of plugin, nx or both? I am still seeing this issue 😢

nrwl packages: 13.4.4
nx console idea: 0.37
webstorm: 2021.3.2
macOS m1 

I have invalidated caches and restarted webstorm with same result as initial problem. Please, let me know if I can help diagnosing in any way.

**Comment by petterhoel** [comment]
Thanks. I have not installed from disk before, but I pointed to the `nx-console-idea-plugin-0.38.0.jar` file. I am assuming that was right because the plugin loaded. 

It does not freeze now, but the graph looks odd, and there is an error. Here is a screen dump and a crash report:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/1263775/153014535-eb585a17-387c-472c-b4ed-ee5d05a3a876.png">

```
Details: Current thread: Thread[ApplicationImpl pooled thread 10,4,main] 355407363
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 552676948

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:980)
	at com.intellij.openapi.graph.impl.builder.GraphBuilderImpl.getView(GraphBuilderImpl.java:644)
	at com.github.iguissouma.nxconsole.graph.fileEditor.NxDepGraphComponent.<init>(NxDepGraphComponent.kt:63)
	at com.github.iguissouma.nxconsole.graph.fileEditor.NxDepGraphFileEditor.createGraphComponent$lambda-1(NxDepGraphFileEditor.kt:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:298)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)```

**Comment by iguissouma** [comment]
For the view it's a default option show grid that's checked.
Please uncheck it, I will try to make it not checked by default.

<img width="845" alt="Screenshot 2022-02-08 at 19 04 04" src="https://user-images.githubusercontent.com/9085108/153048506-dc7f45bd-403a-4204-a14d-92941ccebcfd.png">

I dont reproduce the error but I will see.

**Comment by petterhoel** [comment]
Ah, I was unaware of the context menu, thanks. 

Unchecked by default would be great. I would also prefer if my last used view was remembered (or a way to toggle such a setting). Now it reverts back to initial view if I close the file and then revisit. 

The error is inconsistent for me. It occurs when opening `nx.json` or toggling graph mode, but not every time. Could perhaps indicate some kind of race condition? However it does not seem to interfere with functionality. Once in graph mode there is no errors. And webstorm never freezes like before. So my issue is resolved. Feel free to close this issue when you publish 0.38.0 😄
